suppressPackageStartupMessages({library(Matrix);library(spacexr);library(SummarizedExperiment);library(SpatialExperiment)})
root <- "/Users/georicl/Documents/sc_sncell_github"
args <- commandArgs(trailingOnly=TRUE)
donors <- if(length(args)) args else c("CID3941","CID3948","CID4461")
stopifnot(all(donors %in% c("CID3941","CID3948","CID4461")))
for(donor in donors) {
  data <- file.path(root,"data/processed/Wu2021_tcell_validation_v1",donor)
  output <- file.path(root,"results/Wu2021_tcell_validation_v1",donor)
  sp_meta <- read.csv(file.path(data,"spatial_metadata.csv"),row.names=1,check.names=FALSE)
  genes <- read.delim(file.path(data,"genes.tsv"),header=FALSE)[[1]]
  sp_counts <- as(readMM(file.path(data,"spatial_counts.mtx")),"CsparseMatrix")
  rownames(sp_counts) <- genes;colnames(sp_counts) <- rownames(sp_meta)
  stopifnot(all(colSums(sp_counts)==sp_meta$nUMI))
  spatial <- SpatialExperiment(assays=list(counts=sp_counts),colData=S4Vectors::DataFrame(sp_meta),spatialCoords=as.matrix(sp_meta[,c("x","y")]))
  for(variant in c("baseline","donor_balanced","epithelial_split","balanced_split")) {
    reference_dir <- if(variant=="baseline") file.path(root,"data/processed/Wu2021_known_composition_v1") else file.path(root,"data/processed/Wu2021_reference_comparison_v1",variant)
    inp <- file.path(data,variant);out <- file.path(output,variant)
    dir.create(inp,showWarnings=FALSE);dir.create(out,showWarnings=FALSE)
    cat("START",donor,variant,format(Sys.time()),"\n")
    meta <- read.csv(file.path(reference_dir,"reference_metadata.csv"),row.names=1,check.names=FALSE)
    counts <- as(readMM(file.path(reference_dir,"reference_counts.mtx")),"CsparseMatrix")
    stopifnot(identical(genes,read.delim(file.path(reference_dir,"genes.tsv"),header=FALSE)[[1]]),all(meta$donor_id %in% c("CID4471","CID4535")),all(colSums(counts)==meta$nUMI),all(table(meta$reference_label[meta$nUMI>=100])>=25))
    rownames(counts) <- genes;colnames(counts) <- rownames(meta);meta$reference_label <- factor(meta$reference_label)
    reference <- SummarizedExperiment(assays=list(counts=counts),colData=S4Vectors::DataFrame(meta))
    set.seed(9);start <- Sys.time()
    prepared <- createRctd(spatial,reference,cell_type_col="reference_label",ref_UMI_min=100,ref_n_cells_min=25)
    saveRDS(prepared,file.path(inp,"rctd_preprocessed.rds"))
    writeLines(prepared$internal_vars$gene_list_reg,file.path(out,"rctd_selected_genes.txt"))
    result <- runRctd(prepared,rctd_mode="full",max_cores=2)
    saveRDS(result,file.path(inp,"rctd_result.rds"))
    weights <- as.matrix(t(assay(result,"weights")))
    stopifnot(nrow(weights)==nrow(sp_meta),setequal(rownames(weights),rownames(sp_meta)),all(is.finite(weights)),all(weights>=0),all(rowSums(weights)>0))
    write.csv(weights,file.path(out,"rctd_raw_weights.csv"))
    write.csv(weights/rowSums(weights),file.path(out,"rctd_relative_weights.csv"))
    capture.output(sessionInfo(),file=file.path(out,"rctd_sessionInfo.txt"))
    saveRDS(list(seed=9,config=prepared$config,mode="full",max_cores=2,elapsed_seconds=as.numeric(difftime(Sys.time(),start,units="secs"))),file.path(inp,"rctd_run_record.rds"))
    cat("DONE",donor,variant,format(Sys.time()),"\n")
  }
}
