suppressPackageStartupMessages({library(Matrix);library(spacexr);library(SummarizedExperiment);library(SpatialExperiment)})
root <- "/Users/georicl/Documents/sc_sncell_github"
base <- file.path(root,"data/processed/Wu2021_known_composition_v1")
data <- file.path(root,"data/processed/Wu2021_coarse_T_v1")
output <- file.path(root,"results/Wu2021_coarse_T_v1")
meta <- read.csv(file.path(data,"reference_metadata.csv"),row.names=1,check.names=FALSE)
genes <- read.delim(file.path(base,"genes.tsv"),header=FALSE)[[1]]
counts <- as(readMM(file.path(base,"reference_counts.mtx")),"CsparseMatrix")
rownames(counts) <- genes;colnames(counts) <- rownames(meta)
stopifnot(all(colSums(counts)==meta$nUMI),all(table(meta$reference_label[meta$nUMI>=100])>=25))
meta$reference_label <- factor(meta$reference_label)
reference <- SummarizedExperiment(assays=list(counts=counts),colData=S4Vectors::DataFrame(meta))
donors <- commandArgs(trailingOnly=TRUE)
if(!length(donors)) donors <- c("CID4067","CID4463","CID3941","CID3948","CID4461")
stopifnot(all(donors %in% c("CID4067","CID4463","CID3941","CID3948","CID4461")))
for(donor in donors) {
  source <- if(donor=="CID4067") base else if(donor=="CID4463") file.path(root,"data/processed/Wu2021_independent_validation_v1") else file.path(root,"data/processed/Wu2021_tcell_validation_v1",donor)
  inp <- file.path(data,donor);out <- file.path(output,donor)
  dir.create(inp,showWarnings=FALSE);dir.create(out,showWarnings=FALSE)
  cat("START",donor,format(Sys.time()),"\n")
  sp_meta <- read.csv(file.path(source,"spatial_metadata.csv"),row.names=1,check.names=FALSE)
  x <- as(readMM(file.path(source,"spatial_counts.mtx")),"CsparseMatrix")
  stopifnot(identical(genes,read.delim(file.path(source,"genes.tsv"),header=FALSE)[[1]]),all(colSums(x)==sp_meta$nUMI))
  rownames(x)<-genes;colnames(x)<-rownames(sp_meta)
  spatial <- SpatialExperiment(assays=list(counts=x),colData=S4Vectors::DataFrame(sp_meta),spatialCoords=as.matrix(sp_meta[,c("x","y")]))
  set.seed(9);start<-Sys.time()
  prepared<-createRctd(spatial,reference,cell_type_col="reference_label",ref_UMI_min=100,ref_n_cells_min=25)
  saveRDS(prepared,file.path(inp,"rctd_preprocessed.rds"))
  result<-runRctd(prepared,rctd_mode="full",max_cores=2)
  saveRDS(result,file.path(inp,"rctd_result.rds"))
  weights<-as.matrix(t(assay(result,"weights")))
  stopifnot(nrow(weights)==nrow(sp_meta),all(is.finite(weights)),all(weights>=0),all(rowSums(weights)>0))
  write.csv(weights,file.path(out,"rctd_raw_weights.csv"));write.csv(weights/rowSums(weights),file.path(out,"rctd_relative_weights.csv"))
  writeLines(prepared$internal_vars$gene_list_reg,file.path(out,"rctd_selected_genes.txt"))
  saveRDS(list(seed=9,config=prepared$config,mode="full",max_cores=2,elapsed_seconds=as.numeric(difftime(Sys.time(),start,units="secs"))),file.path(inp,"rctd_run_record.rds"))
  capture.output(sessionInfo(),file=file.path(out,"rctd_sessionInfo.txt"))
  cat("DONE",donor,format(Sys.time()),"\n")
}
